name: wisp_mental_health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  flutter_riverpod: any
  freezed_annotation: any
  json_annotation: any
  riverpod_annotation: any
  audioplayers: any
  firebase_core: any
  firebase_auth: any
  flutter_secure_storage: any
  go_router: any
  http: ^1.6.0

dependency_overrides:
  analyzer: 11.0.0
  meta: 1.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  freezed: any
  json_serializable: any
  riverpod_generator: any
  riverpod_lint: any

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
