name: wisp_mental_health
description: "WISP - a calm space for daily reflections."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  flutter_riverpod: ^2.6.1
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  go_router: ^17.1.0
  http: ^1.6.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
