// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQfba6bqpOC-DWRAL3NyLRgsoxgh8nwH8',
    appId: '1:195188338176:web:011954b75b43e1fcb2b2e5',
    messagingSenderId: '195188338176',
    projectId: 'wisp-mental-health-app',
    authDomain: 'wisp-mental-health-app.firebaseapp.com',
    storageBucket: 'wisp-mental-health-app.firebasestorage.app',
    measurementId: 'G-MMR8YZRE0J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQh1Dirl0BkVcIeB0unbN7QcPI50NNFB0',
    appId: '1:195188338176:ios:d5e66dc3be6a440fb2b2e5',
    messagingSenderId: '195188338176',
    projectId: 'wisp-mental-health-app',
    storageBucket: 'wisp-mental-health-app.firebasestorage.app',
    iosClientId: '195188338176-4qr50ge2c6an7hijkt7ffonashd9suk5.apps.googleusercontent.com',
    iosBundleId: 'com.wisp.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCuPiqKLhWcY5nHXv1VZf5QkwHCBwSVU',
    appId: '1:195188338176:android:7af4e6a6a3365b7bb2b2e5',
    messagingSenderId: '195188338176',
    projectId: 'wisp-mental-health-app',
    storageBucket: 'wisp-mental-health-app.firebasestorage.app',
  );

}